// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core/config/dicom_config.dart';
import 'api/core/models/dicom_frame_result.dart';
import 'api/core/models/dicom_metadata.dart';
import 'api/core/models/dicom_series.dart';
import 'api/core/utils/process_dicom_file.dart';
import 'api/core/utils/series_loader.dart';
import 'api/init.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1282745309;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'flutter_dicom',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<DicomConfig> crateApiCoreConfigDicomConfigDicomConfigDefault();

  Future<DicomFrameResult>
      crateApiCoreModelsDicomFrameResultDicomFrameResultNew(
          {required DicomFrameResult result});

  Future<DicomMetadata> crateApiCoreModelsDicomMetadataDicomMetadataDefault();

  Future<void> crateApiInitInitApp();

  Future<DicomFrameResult> crateApiInitLoadDicom(
      {required String path, required DicomConfig config});

  Future<DicomFrameResult> crateApiInitLoadDicomFromBytes(
      {required List<int> bytes, required DicomConfig config});

  Future<List<DicomSeries>> crateApiInitLoadDicomSeriesFromDir(
      {required String dirPath});

  Future<List<DicomSeries>> crateApiInitLoadDicomSeriesFromFiles(
      {required List<String> paths});

  Future<DicomFrameResult> crateApiCoreUtilsProcessDicomFileProcessDicomFile(
      {required String path, required DicomConfig config});

  Future<DicomFrameResult>
      crateApiCoreUtilsProcessDicomFileProcessDicomFromBytes(
          {required List<int> bytes, required DicomConfig config});

  Future<List<DicomSeries>>
      crateApiCoreUtilsSeriesLoaderSeriesLoaderLoadDirectory(
          {required String dirPath});

  Future<List<DicomSeries>> crateApiCoreUtilsSeriesLoaderSeriesLoaderLoadFiles(
      {required List<String> paths});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<DicomConfig> crateApiCoreConfigDicomConfigDicomConfigDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreConfigDicomConfigDicomConfigDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCoreConfigDicomConfigDicomConfigDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "dicom_config_default",
        argNames: [],
      );

  @override
  Future<DicomFrameResult>
      crateApiCoreModelsDicomFrameResultDicomFrameResultNew(
          {required DicomFrameResult result}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_dicom_frame_result(result, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: null,
      ),
      constMeta:
          kCrateApiCoreModelsDicomFrameResultDicomFrameResultNewConstMeta,
      argValues: [result],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreModelsDicomFrameResultDicomFrameResultNewConstMeta =>
          const TaskConstMeta(
            debugName: "dicom_frame_result_new",
            argNames: ["result"],
          );

  @override
  Future<DicomMetadata> crateApiCoreModelsDicomMetadataDicomMetadataDefault() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_metadata,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCoreModelsDicomMetadataDicomMetadataDefaultConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreModelsDicomMetadataDicomMetadataDefaultConstMeta =>
          const TaskConstMeta(
            debugName: "dicom_metadata_default",
            argNames: [],
          );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiInitInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<DicomFrameResult> crateApiInitLoadDicom(
      {required String path, required DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitLoadDicomConstMeta,
      argValues: [path, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoadDicomConstMeta => const TaskConstMeta(
        debugName: "load_dicom",
        argNames: ["path", "config"],
      );

  @override
  Future<DicomFrameResult> crateApiInitLoadDicomFromBytes(
      {required List<int> bytes, required DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitLoadDicomFromBytesConstMeta,
      argValues: [bytes, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoadDicomFromBytesConstMeta =>
      const TaskConstMeta(
        debugName: "load_dicom_from_bytes",
        argNames: ["bytes", "config"],
      );

  @override
  Future<List<DicomSeries>> crateApiInitLoadDicomSeriesFromDir(
      {required String dirPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dirPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dicom_series,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitLoadDicomSeriesFromDirConstMeta,
      argValues: [dirPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoadDicomSeriesFromDirConstMeta =>
      const TaskConstMeta(
        debugName: "load_dicom_series_from_dir",
        argNames: ["dirPath"],
      );

  @override
  Future<List<DicomSeries>> crateApiInitLoadDicomSeriesFromFiles(
      {required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dicom_series,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiInitLoadDicomSeriesFromFilesConstMeta,
      argValues: [paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiInitLoadDicomSeriesFromFilesConstMeta =>
      const TaskConstMeta(
        debugName: "load_dicom_series_from_files",
        argNames: ["paths"],
      );

  @override
  Future<DicomFrameResult> crateApiCoreUtilsProcessDicomFileProcessDicomFile(
      {required String path, required DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreUtilsProcessDicomFileProcessDicomFileConstMeta,
      argValues: [path, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreUtilsProcessDicomFileProcessDicomFileConstMeta =>
          const TaskConstMeta(
            debugName: "process_dicom_file",
            argNames: ["path", "config"],
          );

  @override
  Future<DicomFrameResult>
      crateApiCoreUtilsProcessDicomFileProcessDicomFromBytes(
          {required List<int> bytes, required DicomConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        sse_encode_box_autoadd_dicom_config(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_dicom_frame_result,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiCoreUtilsProcessDicomFileProcessDicomFromBytesConstMeta,
      argValues: [bytes, config],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreUtilsProcessDicomFileProcessDicomFromBytesConstMeta =>
          const TaskConstMeta(
            debugName: "process_dicom_from_bytes",
            argNames: ["bytes", "config"],
          );

  @override
  Future<List<DicomSeries>>
      crateApiCoreUtilsSeriesLoaderSeriesLoaderLoadDirectory(
          {required String dirPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dirPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dicom_series,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiCoreUtilsSeriesLoaderSeriesLoaderLoadDirectoryConstMeta,
      argValues: [dirPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreUtilsSeriesLoaderSeriesLoaderLoadDirectoryConstMeta =>
          const TaskConstMeta(
            debugName: "series_loader_load_directory",
            argNames: ["dirPath"],
          );

  @override
  Future<List<DicomSeries>> crateApiCoreUtilsSeriesLoaderSeriesLoaderLoadFiles(
      {required List<String> paths}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(paths, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_dicom_series,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiCoreUtilsSeriesLoaderSeriesLoaderLoadFilesConstMeta,
      argValues: [paths],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiCoreUtilsSeriesLoaderSeriesLoaderLoadFilesConstMeta =>
          const TaskConstMeta(
            debugName: "series_loader_load_files",
            argNames: ["paths"],
          );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DicomConfig dco_decode_box_autoadd_dicom_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dicom_config(raw);
  }

  @protected
  DicomFrameResult dco_decode_box_autoadd_dicom_frame_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dicom_frame_result(raw);
  }

  @protected
  DicomConfig dco_decode_dicom_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DicomConfig(
      autoNormalize: dco_decode_bool(arr[0]),
      skipPixels: dco_decode_bool(arr[1]),
    );
  }

  @protected
  DicomFrameResult dco_decode_dicom_frame_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DicomFrameResult(
      metadata: dco_decode_dicom_metadata(arr[0]),
      pixelData: dco_decode_list_prim_i_16_strict(arr[1]),
    );
  }

  @protected
  DicomMetadata dco_decode_dicom_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 34)
      throw Exception('unexpected arr length: expect 34 but see ${arr.length}');
    return DicomMetadata(
      patientId: dco_decode_String(arr[0]),
      patientName: dco_decode_String(arr[1]),
      studyDate: dco_decode_String(arr[2]),
      seriesDate: dco_decode_String(arr[3]),
      acquisitionDate: dco_decode_String(arr[4]),
      contentDate: dco_decode_String(arr[5]),
      studyDescription: dco_decode_String(arr[6]),
      modality: dco_decode_String(arr[7]),
      studyInstanceUid: dco_decode_String(arr[8]),
      seriesInstanceUid: dco_decode_String(arr[9]),
      sopInstanceUid: dco_decode_String(arr[10]),
      seriesDescription: dco_decode_String(arr[11]),
      bodyPartExamined: dco_decode_String(arr[12]),
      toothInfo: dco_decode_String(arr[13]),
      sliceThickness: dco_decode_f_32(arr[14]),
      instanceNumber: dco_decode_String(arr[15]),
      photometricInterpretation: dco_decode_String(arr[16]),
      width: dco_decode_u_32(arr[17]),
      height: dco_decode_u_32(arr[18]),
      windowCenter: dco_decode_f_32(arr[19]),
      windowWidth: dco_decode_f_32(arr[20]),
      rescaleIntercept: dco_decode_f_32(arr[21]),
      rescaleSlope: dco_decode_f_32(arr[22]),
      samplesPerPixel: dco_decode_u_16(arr[23]),
      bitsAllocated: dco_decode_u_16(arr[24]),
      bitsStored: dco_decode_u_16(arr[25]),
      highBit: dco_decode_u_16(arr[26]),
      pixelRepresentation: dco_decode_u_16(arr[27]),
      pixelSpacing: dco_decode_String(arr[28]),
      imagePositionPatient: dco_decode_String(arr[29]),
      imageOrientationPatient: dco_decode_String(arr[30]),
      sliceLocation: dco_decode_f_32(arr[31]),
      spacingBetweenSlices: dco_decode_f_32(arr[32]),
      numberOfFrames: dco_decode_u_32(arr[33]),
    );
  }

  @protected
  DicomSeries dco_decode_dicom_series(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DicomSeries(
      seriesInstanceUid: dco_decode_String(arr[0]),
      slices: dco_decode_list_dicom_slice(arr[1]),
    );
  }

  @protected
  DicomSlice dco_decode_dicom_slice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DicomSlice(
      filePath: dco_decode_String(arr[0]),
      metadata: dco_decode_dicom_metadata(arr[1]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<DicomSeries> dco_decode_list_dicom_series(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dicom_series).toList();
  }

  @protected
  List<DicomSlice> dco_decode_list_dicom_slice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dicom_slice).toList();
  }

  @protected
  Int16List dco_decode_list_prim_i_16_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Int16List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SeriesLoader dco_decode_series_loader(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 0)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return SeriesLoader();
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DicomConfig sse_decode_box_autoadd_dicom_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dicom_config(deserializer));
  }

  @protected
  DicomFrameResult sse_decode_box_autoadd_dicom_frame_result(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dicom_frame_result(deserializer));
  }

  @protected
  DicomConfig sse_decode_dicom_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_autoNormalize = sse_decode_bool(deserializer);
    var var_skipPixels = sse_decode_bool(deserializer);
    return DicomConfig(
        autoNormalize: var_autoNormalize, skipPixels: var_skipPixels);
  }

  @protected
  DicomFrameResult sse_decode_dicom_frame_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_metadata = sse_decode_dicom_metadata(deserializer);
    var var_pixelData = sse_decode_list_prim_i_16_strict(deserializer);
    return DicomFrameResult(metadata: var_metadata, pixelData: var_pixelData);
  }

  @protected
  DicomMetadata sse_decode_dicom_metadata(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_patientId = sse_decode_String(deserializer);
    var var_patientName = sse_decode_String(deserializer);
    var var_studyDate = sse_decode_String(deserializer);
    var var_seriesDate = sse_decode_String(deserializer);
    var var_acquisitionDate = sse_decode_String(deserializer);
    var var_contentDate = sse_decode_String(deserializer);
    var var_studyDescription = sse_decode_String(deserializer);
    var var_modality = sse_decode_String(deserializer);
    var var_studyInstanceUid = sse_decode_String(deserializer);
    var var_seriesInstanceUid = sse_decode_String(deserializer);
    var var_sopInstanceUid = sse_decode_String(deserializer);
    var var_seriesDescription = sse_decode_String(deserializer);
    var var_bodyPartExamined = sse_decode_String(deserializer);
    var var_toothInfo = sse_decode_String(deserializer);
    var var_sliceThickness = sse_decode_f_32(deserializer);
    var var_instanceNumber = sse_decode_String(deserializer);
    var var_photometricInterpretation = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_windowCenter = sse_decode_f_32(deserializer);
    var var_windowWidth = sse_decode_f_32(deserializer);
    var var_rescaleIntercept = sse_decode_f_32(deserializer);
    var var_rescaleSlope = sse_decode_f_32(deserializer);
    var var_samplesPerPixel = sse_decode_u_16(deserializer);
    var var_bitsAllocated = sse_decode_u_16(deserializer);
    var var_bitsStored = sse_decode_u_16(deserializer);
    var var_highBit = sse_decode_u_16(deserializer);
    var var_pixelRepresentation = sse_decode_u_16(deserializer);
    var var_pixelSpacing = sse_decode_String(deserializer);
    var var_imagePositionPatient = sse_decode_String(deserializer);
    var var_imageOrientationPatient = sse_decode_String(deserializer);
    var var_sliceLocation = sse_decode_f_32(deserializer);
    var var_spacingBetweenSlices = sse_decode_f_32(deserializer);
    var var_numberOfFrames = sse_decode_u_32(deserializer);
    return DicomMetadata(
        patientId: var_patientId,
        patientName: var_patientName,
        studyDate: var_studyDate,
        seriesDate: var_seriesDate,
        acquisitionDate: var_acquisitionDate,
        contentDate: var_contentDate,
        studyDescription: var_studyDescription,
        modality: var_modality,
        studyInstanceUid: var_studyInstanceUid,
        seriesInstanceUid: var_seriesInstanceUid,
        sopInstanceUid: var_sopInstanceUid,
        seriesDescription: var_seriesDescription,
        bodyPartExamined: var_bodyPartExamined,
        toothInfo: var_toothInfo,
        sliceThickness: var_sliceThickness,
        instanceNumber: var_instanceNumber,
        photometricInterpretation: var_photometricInterpretation,
        width: var_width,
        height: var_height,
        windowCenter: var_windowCenter,
        windowWidth: var_windowWidth,
        rescaleIntercept: var_rescaleIntercept,
        rescaleSlope: var_rescaleSlope,
        samplesPerPixel: var_samplesPerPixel,
        bitsAllocated: var_bitsAllocated,
        bitsStored: var_bitsStored,
        highBit: var_highBit,
        pixelRepresentation: var_pixelRepresentation,
        pixelSpacing: var_pixelSpacing,
        imagePositionPatient: var_imagePositionPatient,
        imageOrientationPatient: var_imageOrientationPatient,
        sliceLocation: var_sliceLocation,
        spacingBetweenSlices: var_spacingBetweenSlices,
        numberOfFrames: var_numberOfFrames);
  }

  @protected
  DicomSeries sse_decode_dicom_series(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_seriesInstanceUid = sse_decode_String(deserializer);
    var var_slices = sse_decode_list_dicom_slice(deserializer);
    return DicomSeries(
        seriesInstanceUid: var_seriesInstanceUid, slices: var_slices);
  }

  @protected
  DicomSlice sse_decode_dicom_slice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filePath = sse_decode_String(deserializer);
    var var_metadata = sse_decode_dicom_metadata(deserializer);
    return DicomSlice(filePath: var_filePath, metadata: var_metadata);
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt16();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<DicomSeries> sse_decode_list_dicom_series(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DicomSeries>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dicom_series(deserializer));
    }
    return ans_;
  }

  @protected
  List<DicomSlice> sse_decode_list_dicom_slice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DicomSlice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dicom_slice(deserializer));
    }
    return ans_;
  }

  @protected
  Int16List sse_decode_list_prim_i_16_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt16List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SeriesLoader sse_decode_series_loader(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SeriesLoader();
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dicom_config(
      DicomConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_dicom_frame_result(
      DicomFrameResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_frame_result(self, serializer);
  }

  @protected
  void sse_encode_dicom_config(DicomConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.autoNormalize, serializer);
    sse_encode_bool(self.skipPixels, serializer);
  }

  @protected
  void sse_encode_dicom_frame_result(
      DicomFrameResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dicom_metadata(self.metadata, serializer);
    sse_encode_list_prim_i_16_strict(self.pixelData, serializer);
  }

  @protected
  void sse_encode_dicom_metadata(DicomMetadata self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.patientId, serializer);
    sse_encode_String(self.patientName, serializer);
    sse_encode_String(self.studyDate, serializer);
    sse_encode_String(self.seriesDate, serializer);
    sse_encode_String(self.acquisitionDate, serializer);
    sse_encode_String(self.contentDate, serializer);
    sse_encode_String(self.studyDescription, serializer);
    sse_encode_String(self.modality, serializer);
    sse_encode_String(self.studyInstanceUid, serializer);
    sse_encode_String(self.seriesInstanceUid, serializer);
    sse_encode_String(self.sopInstanceUid, serializer);
    sse_encode_String(self.seriesDescription, serializer);
    sse_encode_String(self.bodyPartExamined, serializer);
    sse_encode_String(self.toothInfo, serializer);
    sse_encode_f_32(self.sliceThickness, serializer);
    sse_encode_String(self.instanceNumber, serializer);
    sse_encode_String(self.photometricInterpretation, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_f_32(self.windowCenter, serializer);
    sse_encode_f_32(self.windowWidth, serializer);
    sse_encode_f_32(self.rescaleIntercept, serializer);
    sse_encode_f_32(self.rescaleSlope, serializer);
    sse_encode_u_16(self.samplesPerPixel, serializer);
    sse_encode_u_16(self.bitsAllocated, serializer);
    sse_encode_u_16(self.bitsStored, serializer);
    sse_encode_u_16(self.highBit, serializer);
    sse_encode_u_16(self.pixelRepresentation, serializer);
    sse_encode_String(self.pixelSpacing, serializer);
    sse_encode_String(self.imagePositionPatient, serializer);
    sse_encode_String(self.imageOrientationPatient, serializer);
    sse_encode_f_32(self.sliceLocation, serializer);
    sse_encode_f_32(self.spacingBetweenSlices, serializer);
    sse_encode_u_32(self.numberOfFrames, serializer);
  }

  @protected
  void sse_encode_dicom_series(DicomSeries self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.seriesInstanceUid, serializer);
    sse_encode_list_dicom_slice(self.slices, serializer);
  }

  @protected
  void sse_encode_dicom_slice(DicomSlice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.filePath, serializer);
    sse_encode_dicom_metadata(self.metadata, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt16(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dicom_series(
      List<DicomSeries> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dicom_series(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dicom_slice(
      List<DicomSlice> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dicom_slice(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_i_16_strict(
      Int16List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt16List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_series_loader(SeriesLoader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
