// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Configuration options for the DICOM processing engine.
///
/// Use this struct to tune the balance between precision and performance.
class DicomConfig {
  /// Recompute window center/width from the decoded pixel histogram even
  /// when the header provides values. Useful for modalities with missing
  /// or unreliable windowing tags (MR, XA, US).
  final bool autoNormalize;

  /// If true, the Rust engine will only parse the file metadata (tags) and
  /// skip the expensive pixel data extraction. This is useful for building
  /// fast metadata viewers or file explorers.
  final bool skipPixels;

  /// Zero-based frame index for multi-frame files (NumberOfFrames > 1).
  /// Out-of-range values fall back to frame 0.
  final int frameIndex;

  const DicomConfig({
    required this.autoNormalize,
    required this.skipPixels,
    required this.frameIndex,
  });

  /// Provides the standard production-ready defaults:
  /// - auto_normalize: false
  /// - skip_pixels: false
  /// - frame_index: 0
  static Future<DicomConfig> default_() =>
      RustLib.instance.api.crateApiCoreConfigDicomConfigDicomConfigDefault();

  @override
  int get hashCode =>
      autoNormalize.hashCode ^ skipPixels.hashCode ^ frameIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DicomConfig &&
          runtimeType == other.runtimeType &&
          autoNormalize == other.autoNormalize &&
          skipPixels == other.skipPixels &&
          frameIndex == other.frameIndex;
}
