// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../config/dicom_config.dart';
import '../models/dicom_frame_result.dart';
import '../models/dicom_metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<DicomFrameResult> processDicomFile({
  required String path,
  required DicomConfig config,
}) => RustLib.instance.api.crateApiCoreUtilsProcessDicomFileProcessDicomFile(
  path: path,
  config: config,
);
