// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../models/dicom_metadata.dart';
import '../models/dicom_series.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class SeriesLoader {
  const SeriesLoader();

  /// Loads all DICOM files in a directory, applies a sorting strategy, and groups them by Series Instance UID.
  static Future<List<DicomSeries>> loadDirectory({required String dirPath}) =>
      RustLib.instance.api
          .crateApiCoreUtilsSeriesLoaderSeriesLoaderLoadDirectory(
              dirPath: dirPath);

  /// Loads a specific set of DICOM files.
  static Future<List<DicomSeries>> loadFiles({required List<String> paths}) =>
      RustLib.instance.api
          .crateApiCoreUtilsSeriesLoaderSeriesLoaderLoadFiles(paths: paths);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesLoader && runtimeType == other.runtimeType;
}
