// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';
import '../models/dicom_metadata.dart';
import '../models/dicom_series.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<[DicomSlice]>>
abstract class DicomSlice implements RustOpaqueInterface {}

abstract class SeriesSortStrategy {
  Future<void> sort({required final List<DicomSlice> slices});
}

/// Sorts slices by their instance number (fallback when spatial info is missing).
class InstanceNumberSorter {
  const InstanceNumberSorter();

  Future<void> sort({required final DicomSlice slices}) => RustLib.instance.api
      .crateApiCoreUtilsSeriesSorterInstanceNumberSorterSort(
          that: this, slices: slices);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is InstanceNumberSorter && runtimeType == other.runtimeType;
}

/// Sorts slices by their spatial slice location (Z-axis).
class SpatialSorter {
  const SpatialSorter();

  Future<void> sort({required final DicomSlice slices}) =>
      RustLib.instance.api.crateApiCoreUtilsSeriesSorterSpatialSorterSort(
          that: this, slices: slices);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(final Object other) =>
      identical(this, other) ||
      other is SpatialSorter && runtimeType == other.runtimeType;
}
