

/// Represents the extracted medical metadata from a DICOM file header.
///
/// This struct contains critical parameters for clinical rendering,
/// including spatial dimensions, windowing defaults, and patient identity.
#[derive(Debug, Clone)]
pub struct DicomMetadata {
    pub patient_id: String,
    pub patient_name: String,
    pub study_date: String,
    pub series_date: String,
    pub acquisition_date: String,
    pub content_date: String,
    pub study_description: String,
    pub modality: String,
    pub study_instance_uid: String,
    pub series_instance_uid: String,
    pub sop_instance_uid: String,
    pub series_description: String,
    pub body_part_examined: String,
    pub tooth_info: String,
    pub slice_thickness: f32,
    pub instance_number: String,
    pub photometric_interpretation: String,
    pub width: u32,
    pub height: u32,
    pub window_center: f32,
    pub window_width: f32,
    pub rescale_intercept: f32,
    pub rescale_slope: f32,
    pub samples_per_pixel: u16,
    pub bits_allocated: u16,
    pub bits_stored: u16,
    pub high_bit: u16,
    pub pixel_representation: u16,
    pub pixel_spacing: String,
    pub image_position_patient: String,
    pub image_orientation_patient: String,
    pub slice_location: f32,
    pub spacing_between_slices: f32,
    pub number_of_frames: u32,
}

impl Default for DicomMetadata {
    fn default() -> Self {
        Self {
            patient_id: "Unknown".to_string(),
            patient_name: "Unknown".to_string(),
            study_date: "Unknown".to_string(),
            series_date: "Unknown".to_string(),
            acquisition_date: "Unknown".to_string(),
            content_date: "Unknown".to_string(),
            study_description: "Unknown".to_string(),
            modality: "Unknown".to_string(),
            study_instance_uid: "Unknown".to_string(),
            series_instance_uid: "Unknown".to_string(),
            sop_instance_uid: "Unknown".to_string(),
            series_description: "Unknown".to_string(),
            body_part_examined: "Unknown".to_string(),
            tooth_info: "".to_string(),
            slice_thickness: 0.0,
            instance_number: "Unknown".to_string(),
            photometric_interpretation: "MONOCHROME2".to_string(),
            width: 0,
            height: 0,
            window_center: 40.0,
            window_width: 400.0,
            rescale_intercept: 0.0,
            rescale_slope: 1.0,
            samples_per_pixel: 1,
            bits_allocated: 16,
            bits_stored: 16,
            high_bit: 15,
            pixel_representation: 0,
            pixel_spacing: "".to_string(),
            image_position_patient: "".to_string(),
            image_orientation_patient: "".to_string(),
            slice_location: 0.0,
            spacing_between_slices: 0.0,
            number_of_frames: 1,
        }
    }
}
