// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class DicomMetadata {
  final int width;
  final int height;
  final double windowCenter;
  final double windowWidth;
  final double rescaleIntercept;
  final double rescaleSlope;
  final String patientName;

  const DicomMetadata({
    required this.width,
    required this.height,
    required this.windowCenter,
    required this.windowWidth,
    required this.rescaleIntercept,
    required this.rescaleSlope,
    required this.patientName,
  });

  @override
  int get hashCode =>
      width.hashCode ^
      height.hashCode ^
      windowCenter.hashCode ^
      windowWidth.hashCode ^
      rescaleIntercept.hashCode ^
      rescaleSlope.hashCode ^
      patientName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DicomMetadata &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height &&
          windowCenter == other.windowCenter &&
          windowWidth == other.windowWidth &&
          rescaleIntercept == other.rescaleIntercept &&
          rescaleSlope == other.rescaleSlope &&
          patientName == other.patientName;
}
