// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Represents the extracted medical metadata from a DICOM file header.
///
/// This struct contains critical parameters for clinical rendering,
/// including spatial dimensions, windowing defaults, and patient identity.
class DicomMetadata {
  final String patientId;
  final String patientName;
  final String studyDate;
  final String seriesDate;
  final String acquisitionDate;
  final String contentDate;
  final String studyDescription;
  final String modality;
  final String studyInstanceUid;
  final String seriesInstanceUid;
  final String sopInstanceUid;
  final String seriesDescription;
  final String bodyPartExamined;
  final String toothInfo;
  final double sliceThickness;
  final String instanceNumber;
  final String photometricInterpretation;
  final int width;
  final int height;
  final double windowCenter;
  final double windowWidth;
  final double rescaleIntercept;
  final double rescaleSlope;
  final int samplesPerPixel;
  final int bitsAllocated;
  final int bitsStored;
  final int highBit;
  final int pixelRepresentation;
  final String pixelSpacing;
  final String imagePositionPatient;
  final String imageOrientationPatient;
  final double sliceLocation;
  final double spacingBetweenSlices;
  final int numberOfFrames;

  const DicomMetadata({
    required this.patientId,
    required this.patientName,
    required this.studyDate,
    required this.seriesDate,
    required this.acquisitionDate,
    required this.contentDate,
    required this.studyDescription,
    required this.modality,
    required this.studyInstanceUid,
    required this.seriesInstanceUid,
    required this.sopInstanceUid,
    required this.seriesDescription,
    required this.bodyPartExamined,
    required this.toothInfo,
    required this.sliceThickness,
    required this.instanceNumber,
    required this.photometricInterpretation,
    required this.width,
    required this.height,
    required this.windowCenter,
    required this.windowWidth,
    required this.rescaleIntercept,
    required this.rescaleSlope,
    required this.samplesPerPixel,
    required this.bitsAllocated,
    required this.bitsStored,
    required this.highBit,
    required this.pixelRepresentation,
    required this.pixelSpacing,
    required this.imagePositionPatient,
    required this.imageOrientationPatient,
    required this.sliceLocation,
    required this.spacingBetweenSlices,
    required this.numberOfFrames,
  });

  static Future<DicomMetadata> default_() => RustLib.instance.api
      .crateApiCoreModelsDicomMetadataDicomMetadataDefault();

  @override
  int get hashCode =>
      patientId.hashCode ^
      patientName.hashCode ^
      studyDate.hashCode ^
      seriesDate.hashCode ^
      acquisitionDate.hashCode ^
      contentDate.hashCode ^
      studyDescription.hashCode ^
      modality.hashCode ^
      studyInstanceUid.hashCode ^
      seriesInstanceUid.hashCode ^
      sopInstanceUid.hashCode ^
      seriesDescription.hashCode ^
      bodyPartExamined.hashCode ^
      toothInfo.hashCode ^
      sliceThickness.hashCode ^
      instanceNumber.hashCode ^
      photometricInterpretation.hashCode ^
      width.hashCode ^
      height.hashCode ^
      windowCenter.hashCode ^
      windowWidth.hashCode ^
      rescaleIntercept.hashCode ^
      rescaleSlope.hashCode ^
      samplesPerPixel.hashCode ^
      bitsAllocated.hashCode ^
      bitsStored.hashCode ^
      highBit.hashCode ^
      pixelRepresentation.hashCode ^
      pixelSpacing.hashCode ^
      imagePositionPatient.hashCode ^
      imageOrientationPatient.hashCode ^
      sliceLocation.hashCode ^
      spacingBetweenSlices.hashCode ^
      numberOfFrames.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DicomMetadata &&
          runtimeType == other.runtimeType &&
          patientId == other.patientId &&
          patientName == other.patientName &&
          studyDate == other.studyDate &&
          seriesDate == other.seriesDate &&
          acquisitionDate == other.acquisitionDate &&
          contentDate == other.contentDate &&
          studyDescription == other.studyDescription &&
          modality == other.modality &&
          studyInstanceUid == other.studyInstanceUid &&
          seriesInstanceUid == other.seriesInstanceUid &&
          sopInstanceUid == other.sopInstanceUid &&
          seriesDescription == other.seriesDescription &&
          bodyPartExamined == other.bodyPartExamined &&
          toothInfo == other.toothInfo &&
          sliceThickness == other.sliceThickness &&
          instanceNumber == other.instanceNumber &&
          photometricInterpretation == other.photometricInterpretation &&
          width == other.width &&
          height == other.height &&
          windowCenter == other.windowCenter &&
          windowWidth == other.windowWidth &&
          rescaleIntercept == other.rescaleIntercept &&
          rescaleSlope == other.rescaleSlope &&
          samplesPerPixel == other.samplesPerPixel &&
          bitsAllocated == other.bitsAllocated &&
          bitsStored == other.bitsStored &&
          highBit == other.highBit &&
          pixelRepresentation == other.pixelRepresentation &&
          pixelSpacing == other.pixelSpacing &&
          imagePositionPatient == other.imagePositionPatient &&
          imageOrientationPatient == other.imageOrientationPatient &&
          sliceLocation == other.sliceLocation &&
          spacingBetweenSlices == other.spacingBetweenSlices &&
          numberOfFrames == other.numberOfFrames;
}
