// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'dicom_metadata.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

class DicomSeries {
  final String seriesInstanceUid;
  final List<DicomSlice> slices;

  const DicomSeries({
    required this.seriesInstanceUid,
    required this.slices,
  });

  @override
  int get hashCode => seriesInstanceUid.hashCode ^ slices.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DicomSeries &&
          runtimeType == other.runtimeType &&
          seriesInstanceUid == other.seriesInstanceUid &&
          slices == other.slices;
}

class DicomSlice {
  final String filePath;
  final DicomMetadata metadata;

  const DicomSlice({
    required this.filePath,
    required this.metadata,
  });

  @override
  int get hashCode => filePath.hashCode ^ metadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DicomSlice &&
          runtimeType == other.runtimeType &&
          filePath == other.filePath &&
          metadata == other.metadata;
}
